name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h1>It''s great having you contribute to this project</h1> Thank you for raising an <strong>Issue</strong> and welcome to the community :nerd_face:'
        pr-message: '<h1>It''s great having you contribute to this project</h1> Thank you for creating a <strong>Pull Request</strong> and welcome to the community :nerd_face:'
        footer: 'Join our <a href="https://discord.gg/sgm3mBBBTJ">Discord</a> and <a href="https://github.com/DSCBITDurg/support/issues/new?assignees=&labels=lets+go+DSC&template=invite-me-to-the-org.md&title=Invitation+to+join+DSC">GitHub</a> Organisation ( by raising an issue ) if you havent yet'
