on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: DSCBITDurg
          label: lets go DSC
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<b>Invitation sent for the GitHub Organisation.</b>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}